---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# clinvisx

<!-- badges: start -->
<!-- badges: end -->

clinvisx is configurable Shiny app for visual exploration of clinica multi-omics studies, based on count data. It includes multiple modules to facilitate exploring associations in the results of such studies, as well as showcasing analysis results (i.e. volcano plots).

## Installation

You can install the latest version of clinvisx with:

``` r
devtools::install_github("rhenkin/clinvisx")
```

Note that the command above will only install basic package dependencies -- the modules in the app have dependencies that need to be installed separately. To install all dependencies, you can install clinvsix with the following command:

``` r
devtools::install_github("rhenkin/clinvisx", dependencies = TRUE)
```

## Configuration and usage

Running clinvisx, in addition to all data files, requires writing a .yaml configuration file. There is a vignette detailing how to configure the global aspects of the app and each currently supported module. You can check it on the github pages website or by running `vignette("clinvisx_setup")`. There is also an example file included in the dev folder in this repository.