default:
  golem_name: clinvisx
  golem_version: 0.0.0.9000
  app_prod: no
  available_modules:
  - cohortOverview
  - degModules
  - singleGeneCorr
  - singleVariableCorr
  - geneModulesCorr
  - wholeDataCorr
  - compareTrajGroups
  degModules:
  - degSummary
  - degOverview
production:
  app_prod: yes
dev:
  golem_wd: !expr here::here()
