default:
  golem_name: clinvisx
  golem_version: 0.0.0.9000
  app_prod: no
  available_modules:
  - cohortOverview
  - degModules
  - degSummary
  - degDetails
  - corrModules
  - singleGeneCorr
  - singleVariableCorr
  - geneModulesCorr
  - geneModulesHeatmap
  - multiVariableCorr
  - compareTrajGroups
  - networkViewer
  degModules:
  - degSummary
  - degDetails
  corrModules:
  - singleGeneCorr
  - singleVariableCorr
  - multiVariableCorr
production:
  app_prod: yes
dev:
  golem_wd: !expr here::here()
