---
title: "degDetails"
author: "Rafael Henkin"
date: "12/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages}
library(profvis)
```

```{r load_all}
devtools::load_all()
```

```{r readconfig}
config <- parseConfig(fname = "../../../ramap_test/config.yaml", data_folder = "../../../ramap_test")
```

```{r server_code}
models <- config$data$models
table <- models$Data[[6]]
fc_threshold <- 1
pvalue_threshold <- 0.05 
pflag <- "p.value"

results_table <- prepareResultsTable(
        table,
        fc_threshold,
        pvalue_threshold,
        pflag
        )

```

### Static plot

```{r ggplot}
gg_volcano_plot(results_table,
                        fc_threshold,
                        -log10(pvalue_threshold),
                        pflag,
                        "Gene")
```

### ggplotly

```{r ggplotly}
plotly::ggplotly(gg_volcano_plot(results_table,
                        fc_threshold,
                        -log10(pvalue_threshold),
                        pflag,
                        "Gene")) %>% plotly::toWebGL()
```


### plotly 
```{r plotly}
plotly_volcano_plot(results_table,
                fc_threshold,
                -log10(pvalue_threshold),
                pflag,
                "Gene")
```


## Profiling

```{r profiling}
profvis({ 
  plotly::ggplotly(gg_volcano_plot(results_table,
                        fc_threshold,
                        -log10(pvalue_threshold),
                        pflag,
                        "Gene"))
})
```